#!/usr/bin/env bash

# Save the old HOME so we can reset after script.
# Bower and bower as it is run buy grunt both want
# to touch .local and .config files in $HOME which
# isn't writeable on OSE.  So we set $HOME to
# the REPO_DIR temporarily.
OLD_HOME=$HOME

HOME=$HOME/app-root/runtime
cd ~/repo

echo "INFO: Running npm install"
npm install gulp bower

echo "INFO: Running 'bower install'"
./node_modules/.bin/bower install

echo "INFO: Running 'gulp'"
./node_modules/.bin/gulp

# ##########
# echo "INFO: Running 'bower install'"
# cd $OPENSHIFT_REPO_DIR
# export HOME=$OPENSHIFT_REPO_DIR
# bower install
#
# ##########
# echo "INFO: Running 'gulp'"
# gulp
# #########
export HOME=$OLD_HOME
echo "INFO: HOME is $HOME"
